version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile
    image: svelte
    container_name: dockertut-svelte
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public